### ISSUE TITLE
Clicking on Dendrogram slider produces "NaN" value

### ISSUE THREAD

**Issue by moromis** [GumusLab/clustergrammer#27]
<img width="133" alt="image" src="https://user-images.githubusercontent.com/4188237/193145699-fecc9f5b-692b-4e68-b1e2-5f3bb676f39a.png">
If you click anywhere on the dendrogram slider instead of using the slider circle, it makes the value "NaN" and the dendrograms segment fully.

**Comment by JozefSedlak103** [comment]
Hi @moromis, if this issue is still open, i would like to work on it. Could you assign me to this issue?
Thanks

**Comment by moromis** [comment]
Sure, just assigned it to you. Looking forward to your PR.

**Comment by moromis** [comment]
Released in v0.2.4
